### ISSUE TITLE
Doesn't work on 0.5

### ISSUE THREAD

**Issue by OrbyyOrbinaut** [mayo78/vslicescripts#3]
Error Is shown in the image

![image](https://github.com/user-attachments/assets/bbda6279-1756-4bbc-84fe-b770779aead5)

**Comment by AppleHair** [comment]
And here's the problem...
![Screenshot 2024-09-19 190715](https://github.com/user-attachments/assets/ecc60f95-5afd-4d30-b45b-348c9f34c18c)
We are so cooked this time.

**Comment by AppleHair** [comment]
Well, nevermind. I did it again 💪
